//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessApp.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessApp.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black won.
        /// </summary>
        public static string black_won {
            get {
                return ResourceManager.GetString("black_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string button_confirm {
            get {
                return ResourceManager.GetString("button.confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string button_create {
            get {
                return ResourceManager.GetString("button.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new game.
        /// </summary>
        public static string create_new_game {
            get {
                return ResourceManager.GetString("create_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended.
        /// </summary>
        public static string game_ended {
            get {
                return ResourceManager.GetString("game_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Varient.
        /// </summary>
        public static string game_varient {
            get {
                return ResourceManager.GetString("game_varient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knightmate.
        /// </summary>
        public static string game_varient_knightmate {
            get {
                return ResourceManager.GetString("game_varient.knightmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string game_varient_standard {
            get {
                return ResourceManager.GetString("game_varient.standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        public static string increment {
            get {
                return ResourceManager.GetString("increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment in seconds.
        /// </summary>
        public static string increment_in_seconds {
            get {
                return ResourceManager.GetString("increment_in_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Room.
        /// </summary>
        public static string leave_game_room {
            get {
                return ResourceManager.GetString("leave_game_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes per side.
        /// </summary>
        public static string minutes_per_side {
            get {
                return ResourceManager.GetString("minutes_per_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not provided.
        /// </summary>
        public static string not_provided {
            get {
                return ResourceManager.GetString("not_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string opponent {
            get {
                return ResourceManager.GetString("opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player joined.
        /// </summary>
        public static string player_joined {
            get {
                return ResourceManager.GetString("player_joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player left.
        /// </summary>
        public static string player_left {
            get {
                return ResourceManager.GetString("player_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string side {
            get {
                return ResourceManager.GetString("side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string side_black {
            get {
                return ResourceManager.GetString("side.black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string side_random {
            get {
                return ResourceManager.GetString("side.random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string side_white {
            get {
                return ResourceManager.GetString("side.white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stalemate.
        /// </summary>
        public static string stalemate {
            get {
                return ResourceManager.GetString("stalemate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully connected to the game..
        /// </summary>
        public static string successfully_connected_message {
            get {
                return ResourceManager.GetString("successfully_connected_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first person to come to this URL will play with you..
        /// </summary>
        public static string url_form_first_person_notification {
            get {
                return ResourceManager.GetString("url_form.first_person_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To invite someone to play, give this URL:.
        /// </summary>
        public static string url_form_invite_notification {
            get {
                return ResourceManager.GetString("url_form.invite_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varient.
        /// </summary>
        public static string varient {
            get {
                return ResourceManager.GetString("varient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting....
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white won.
        /// </summary>
        public static string white_won {
            get {
                return ResourceManager.GetString("white_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
    }
}
